name: Release WFA
on:
    push:
        branches:
            - master
            - beta
            - next
            - varun-personal/next
jobs:
    test-publish:
        name: Test
        runs-on: ubuntu-latest
        strategy:
          fail-fast: true
          matrix:
            node: [12]
        steps:
            - uses: actions/checkout@v2
            - name: 'registry setup'
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - name: install
              run: npm ci
            - name: test
              if: success()
              run: npm run test
            - name: build
              if: success()
              run: npm run build
            - name: semantic-release
              if: success()
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release --debug
    # publish:
    #     name: Publish
    #     needs: [ test ]
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2
    #         - name: 'registry setup'
    #           uses: actions/setup-node@v1
    #           with:
    #               node-version: 12
    #               registry-url: https://npm.pkg.github.com
    #               scope: '@buddy-git'
    #         - name: install
    #           run: npm ci
    #         - name: build
    #           if: success()
    #           run: npm run build
    #         - name: semantic-release
    #           if: success()
    #           env:
    #             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #             NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #             NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #           run: npx semantic-release --debug